twig:
  default_path: '%kernel.project_dir%/templates'
  form_themes:
  - bootstrap_4_layout.html.twig
  globals:
    categoryRepository: "@App\\Repository\\CategoryRepository"
    subCategoryRepository: "@App\\Repository\\SubCategoryRepository"
    cartServce: "@App\\Cart\\CartService"