<?php

namespace App\Controller\Admin;

use App\Entity\Car;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;

class CarCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Car::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')->onlyOnIndex(),
            AssociationField::new('model'),
            AssociationField::new('engine'),
            AssociationField::new('year'),
            AssociationField::new('transmission')
        ];
    }
    public function configureActions(Actions $actions): Actions
    {
        return parent::configureActions(
            $actions->add(Crud::PAGE_INDEX,
                Action::DETAIL) ->update(Crud::PAGE_INDEX,
                Action::NEW,function (Action $action){
                    return $action->setIcon('fa fa-plus')->setLabel('New VIN');
                })); // TODO: Change the autogenerated stub
    }
    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInPlural('VIN')
            ->setEntityLabelInSingular('VIN');
    }

}
