<?php

namespace App\Controller\Admin;

use App\Entity\User;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\User\UserInterface;

class UserCrudController extends AbstractCrudController
{

    public static function getEntityFqcn(): string
    {
        return User::class;
    }


    public function configureFields(string $pageName): iterable
    {

        return [

            TextField::new('Email')->setRequired(true),
            TextField::new('fullName')->setRequired(true),
            TextField::new('Password')->onlyOnForms()->setFormType(PasswordType::class)->setRequired(true),
            ArrayField::new('Roles')->onlyOnIndex(),
            TextField::new('confirmPassword')->onlyOnForms()->setFormType(PasswordType::class)->setRequired(true),
            DateField::new('createdAt')->onlyOnDetail(),
            DateField::new('updatedAt')->onlyOnIndex()
        ];
    }

    public function configureActions(Actions $actions): Actions
    {
        return parent::configureActions(
            $actions->add(Crud::PAGE_INDEX, Action::DETAIL)
                ->update(Crud::PAGE_INDEX,
                    Action::NEW,function (Action $action){
            return $action->setIcon('fa fa-plus')->setLabel('New Admin');
        })); // TODO: Change the autogenerated stub
    }

}
